# Numpy

In [118]:
import numpy as np

## Index ile elemana erişme

In [119]:
b4=np.arange(1,10)
5*b4

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45])

In [120]:
a=np.random.randint(10, size=10)
a

array([2, 5, 0, 3, 0, 5, 1, 7, 9, 8])

In [121]:
a[0]

2

In [122]:
a[-1]

8

In [123]:
a[0]=100
a

array([100,   5,   0,   3,   0,   5,   1,   7,   9,   8])

In [124]:
m=np.random.randint(10, size=(3,5))
m

array([[9, 5, 4, 3, 7],
       [5, 3, 2, 6, 8],
       [8, 7, 8, 7, 0]])

In [125]:
m[0,0]

9

In [126]:
m[1,4]=99
m

array([[ 9,  5,  4,  3,  7],
       [ 5,  3,  2,  6, 99],
       [ 8,  7,  8,  7,  0]])

## Array Alt Kümeye Erişim (Slice)

In [127]:
a2= np.arange(20,30)
a2

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [128]:
a2[0:3]

array([20, 21, 22])

In [129]:
a2[:3]

array([20, 21, 22])

In [130]:
a2[1::2] #ikişer ikişer ilerle

array([21, 23, 25, 27, 29])

In [131]:
a2[0::2]

array([20, 22, 24, 26, 28])

In [132]:
a2[0::3]

array([20, 23, 26, 29])

In [133]:
#iki boyutlu arrayda slice
a3=np.random.randint(10,size=(5,5))
a3

array([[8, 5, 1, 6, 7],
       [8, 7, 1, 0, 5],
       [4, 7, 2, 6, 6],
       [4, 4, 9, 2, 7],
       [7, 1, 7, 8, 1]])

In [134]:
a3[:,0]

array([8, 8, 4, 4, 7])

In [135]:
a3[:,1]

array([5, 7, 7, 4, 1])

In [136]:
a3[1:,:] #birinci satır tüm sütunlar

array([[8, 7, 1, 0, 5],
       [4, 7, 2, 6, 6],
       [4, 4, 9, 2, 7],
       [7, 1, 7, 8, 1]])

In [137]:
a3[1,:]

array([8, 7, 1, 0, 5])

In [138]:
a3

array([[8, 5, 1, 6, 7],
       [8, 7, 1, 0, 5],
       [4, 7, 2, 6, 6],
       [4, 4, 9, 2, 7],
       [7, 1, 7, 8, 1]])

In [139]:
a3[0:2,0:3]

array([[8, 5, 1],
       [8, 7, 1]])

In [140]:
a3[::,:2]

array([[8, 5],
       [8, 7],
       [4, 7],
       [4, 4],
       [7, 1]])

In [141]:
a3[1:3,0:2]

array([[8, 7],
       [4, 7]])

## Alt Küme Üzerine İşlem

In [142]:
a4= np.random.randint(10, size=(5,5))
a4

array([[1, 3, 4, 3, 3],
       [8, 1, 2, 7, 6],
       [8, 2, 1, 5, 2],
       [6, 1, 7, 3, 8],
       [5, 1, 9, 9, 9]])

In [143]:
alt1=a4[0:3,0:2]
alt1

array([[1, 3],
       [8, 1],
       [8, 2]])

In [144]:
alt1[0,0]=99
alt1

array([[99,  3],
       [ 8,  1],
       [ 8,  2]])

In [145]:
a4

array([[99,  3,  4,  3,  3],
       [ 8,  1,  2,  7,  6],
       [ 8,  2,  1,  5,  2],
       [ 6,  1,  7,  3,  8],
       [ 5,  1,  9,  9,  9]])

In [146]:
a5=np.random.randint(10, size=(5,5))
a5

array([[9, 5, 9, 2, 3],
       [7, 0, 2, 9, 4],
       [6, 6, 2, 7, 2],
       [3, 7, 4, 1, 9],
       [7, 3, 3, 6, 4]])

In [147]:
alt2=a5[0:3,0:2].copy()
alt2

array([[9, 5],
       [7, 0],
       [6, 6]])

In [148]:
alt2[0,0]=66
alt2

array([[66,  5],
       [ 7,  0],
       [ 6,  6]])

In [149]:
a5

array([[9, 5, 9, 2, 3],
       [7, 0, 2, 9, 4],
       [6, 6, 2, 7, 2],
       [3, 7, 4, 1, 9],
       [7, 3, 3, 6, 4]])

## Fancy Index ile Eleman Erişimi

In [150]:
v=np.arange(0,30,3)
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [151]:
v[1]

3

In [152]:
[v[1],v[3],v[5]]

[3, 9, 15]

In [153]:
gtr=[1,3,5]
v[gtr]

array([ 3,  9, 15])

In [155]:
v2=np.arange(9).reshape((3,3))
v2

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [157]:
satir=np.array([0,1])
sutun=np.array([1,2])


In [159]:
v2[satir,sutun] #0. satır 1. sütun
                #1. satır 2. sütun

array([1, 5])

In [161]:
#slice ile fancy
v2[1:, [1,2]]

array([[4, 5],
       [7, 8]])

## Koşullu Eleman İşlemleri

In [162]:
v3=np.array([1,2,3,4,5])
v3

array([1, 2, 3, 4, 5])

In [163]:
v3>5

array([False, False, False, False, False])

In [164]:
v3>=5

array([False, False, False, False,  True])

In [166]:
v3<3

array([ True,  True, False, False, False])

In [168]:
v3[v3<3]

array([1, 2])

In [169]:
v3[v3>=2]

array([2, 3, 4, 5])

In [170]:
v3[v3!=2]

array([1, 3, 4, 5])

In [171]:
v3**3

array([  1,   8,  27,  64, 125], dtype=int32)

## Matematiksel İşlemler

In [172]:
import numpy as np


In [173]:
v4=np.array([1,2,3,4,5])
v4

array([1, 2, 3, 4, 5])

In [174]:
v4-1

array([0, 1, 2, 3, 4])

In [175]:
v4*6

array([ 6, 12, 18, 24, 30])

In [176]:
#ufunc
np.divide(v4,4)

array([0.25, 0.5 , 0.75, 1.  , 1.25])

In [177]:
v4

array([1, 2, 3, 4, 5])

In [178]:
#mutlak değer
v4-6

array([-5, -4, -3, -2, -1])

In [179]:
np.absolute(v4-6)

array([5, 4, 3, 2, 1])

In [180]:
np.sin(90)

0.8939966636005579

In [181]:
np.sin(0)

0.0

In [182]:
np.log(v4)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791])

In [184]:
# ?np = cheatsheet 

In [185]:
np.mean(v4)

3.0

## İki bilinmeyenli denklem

5*x0+x1=12

x0+3*x1=10

In [186]:
d=np.array([[5,1],[1,3]])
z=np.array([12,10])

In [187]:
xd=np.linalg.solve(d,z)
xd

array([1.85714286, 2.71428571])