In [1]:
print("merhaba dünya")

merhaba dünya


# Numpy

Numerical-Python

Bilimsel Hesaplama 

Array/çok boyutlu arraylar

Sabit Tip

Listelere Benzer

In [2]:
a=[1,2,3,4]
b=[2,3,4,5]
a

[1, 2, 3, 4]

In [3]:
b

[2, 3, 4, 5]

In [4]:
ab=[]

In [5]:
for i in range(0,len(a)):
    ab.append(a[i]*b[i])

ab    

[2, 6, 12, 20]

In [6]:
import numpy as np

In [7]:
a2=np.array([1,2,3,4])
b2=np.array([2,3,4,5])
a2*b2

array([ 2,  6, 12, 20])

## Numpy Array'i oluşturma

In [8]:
a3=np.array([1,2,3,4,5])
a3

array([1, 2, 3, 4, 5])

In [9]:
type(a3)

numpy.ndarray

In [10]:
a4=np.array([1,2.5,3,4,5])
a4

array([1. , 2.5, 3. , 4. , 5. ])

In [11]:
a5=np.array([1,2.5,3,4,5], dtype=int)
a5

array([1, 2, 3, 4, 5])

## Sıfırdan Array Oluşturma

In [12]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [13]:
np.ones((3,5),dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [14]:
np.full((3,5),6)

array([[6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6]])

In [15]:
np.arange(0,31,3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [16]:
np.linspace(0,1,10) #0-1 arası 10 sayı üret

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [17]:
np.random.normal(10,4,(3,4)) #ortalaması 10
                            #std 4

array([[ 8.54044698,  9.55170209, 11.8794776 , 13.04726464],
       [17.31192837,  7.63618055, 16.53963274, 10.24625164],
       [ 8.21540972, 17.00141786,  8.32453105, 11.25271617]])

In [18]:
np.random.randint(0,10,(3,3))

array([[7, 8, 5],
       [7, 5, 8],
       [7, 9, 4]])

## Özellikleri
* ndim : boyut sayısı
* shape: boyut bilgisi
* size : toplam eleman sayısı
* dtype: array veri tipi

In [19]:
a6=np.random.randint(10, size=10)
a6

array([2, 7, 6, 4, 0, 5, 9, 4, 1, 7])

In [20]:
a7=np.random.randint(0,10,10)
a7

array([2, 0, 8, 9, 4, 4, 1, 8, 3, 1])

In [21]:
a6.ndim

1

In [22]:
a6.shape

(10,)

In [23]:
a6.size

10

In [24]:
a6.dtype

dtype('int32')

In [25]:
b3= np.random.randint(10, size=(3,5))
b3

array([[2, 0, 9, 9, 6],
       [7, 6, 0, 6, 0],
       [6, 5, 2, 1, 2]])

In [26]:
b3.ndim

2

In [27]:
b3.shape

(3, 5)

In [28]:
b3.size

15

In [29]:
b3.dtype

dtype('int32')

## Yeniden Boyutlandırma (Reshape)

In [30]:
import numpy as np

In [31]:
b4=np.arange(1,10)
b4

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
np.arange(1,10).reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [33]:
b5=b4.reshape((1,9))
b5

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [34]:
b4.ndim

1

In [35]:
b5.ndim

2

## Concat

In [36]:
x1=np.array([1,2,3])
y1=np.array([4,5,6])
c=np.concatenate([x1,y1])
c

array([1, 2, 3, 4, 5, 6])

In [37]:
z1=np.array([7,8,9])
np.concatenate([x1,y1,z1])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
np.concatenate([c,c])

array([1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6])

In [39]:
x2=np.array([[1,2,3],[4,5,6]])
c2=np.concatenate([x2,x2], axis=0)
c2

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [40]:
x3=np.array([[1,2,3],[4,5,6]])
c3=np.concatenate([x3,x3], axis=1)
c3

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

## Array Ayırma (Split)

In [41]:
f=np.array([1,2,3,99,99,3,2,1])
f

array([ 1,  2,  3, 99, 99,  3,  2,  1])

In [42]:
np.split(f,[3,5]) #ilk 3'ü bir, gerisi 5'e kadar

[array([1, 2, 3]), array([99, 99]), array([3, 2, 1])]

In [43]:
f1,f2,f3 =np.split(f,[3,5]) #ilk 3'ü bir, gerisi 5'e kadar
f2

array([99, 99])

In [44]:
#iki boyutlu ayırma

m=np.arange(16).reshape(4,4)
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [45]:
np.vsplit(m,[2]) #2'ye kadar, 2. satıra

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [46]:
np.hsplit(m,[2]) #2'ye kadar, 2. satıra

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

## Array Sıralama (Sorting)

In [47]:
v=np.array([2,1,4,3,5])
v

array([2, 1, 4, 3, 5])

In [48]:
np.sort(v)

array([1, 2, 3, 4, 5])

In [49]:
v

array([2, 1, 4, 3, 5])

In [50]:
5*np.array([1, 2,3])

array([ 5, 10, 15])