<a href="https://colab.research.google.com/github/AhmetSarici/DataScience/blob/ML/Makine%20%C3%96%C4%9Frenmesi/ML_MultipleLineerRegresyon_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [6]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns  
from sklearn.linear_model import LinearRegression

In [5]:
data = pd.read_csv('/content/drive/My Drive/Colab Notebooks/Makine Öğrenmesi/multiple_linear_regression_dataset.csv',sep=';')
data.head()

deneyim  maas  yas
0      0.5  2500   22
1      0.0  2250   21
2      1.0  2750   23
3      5.0  8000   25
4      8.0  9000   28

Simple Linear Regression = 

>**y=b0+b1*x** 

Maaş  = 

>**b0+b1*deneyim**

Multiple LR =

>**b0+ b1*x1 + b2*yaş** ...

Maaş=

>**b0+b1*deneyim+b2*yaş**

Bağımlı Değişken
* Maaş
* Deneyim
* Yaş





x için deneyim ve maaş

In [7]:
x=data.iloc[:,[0,2]].values
y=data.maas.values.reshape(-1,1)

In [8]:
multiple_lr=LinearRegression()
multiple_lr.fit(x,y)

LinearRegression()

In [9]:
b0=multiple_lr.intercept_
b0

array([10376.62747228])

In [11]:
b1_b2=multiple_lr.coef_
b1_b2

array([[1525.50072054, -416.72218625]])

10 yıllık deneyim 35 yaş

5 yıllık deneyim 35 yaş girilirek predict yapılırsa

In [20]:
multiple_lr.predict(np.array([[10,35],[5,35],[3,33]]))

array([[11046.35815877],
       [ 3418.85455609],
       [ 1201.29748752]])